-- ============================================================
-- NewBank Credit Decision Platform
-- Physical Data Model
-- File: 02_create_tables.sql
-- Description: Creates raw tables for the Home Credit dataset.
-- Generated automatically from data/raw CSV headers.
-- ============================================================

-- Table: raw.application_test
CREATE TABLE IF NOT EXISTS raw.application_test (
    "sk_id_curr" TEXT,
    "name_contract_type" TEXT,
    "code_gender" TEXT,
    "flag_own_car" TEXT,
    "flag_own_realty" TEXT,
    "cnt_children" TEXT,
    "amt_income_total" TEXT,
    "amt_credit" TEXT,
    "amt_annuity" TEXT,
    "amt_goods_price" TEXT,
    "name_type_suite" TEXT,
    "name_income_type" TEXT,
    "name_education_type" TEXT,
    "name_family_status" TEXT,
    "name_housing_type" TEXT,
    "region_population_relative" TEXT,
    "days_birth" TEXT,
    "days_employed" TEXT,
    "days_registration" TEXT,
    "days_id_publish" TEXT,
    "own_car_age" TEXT,
    "flag_mobil" TEXT,
    "flag_emp_phone" TEXT,
    "flag_work_phone" TEXT,
    "flag_cont_mobile" TEXT,
    "flag_phone" TEXT,
    "flag_email" TEXT,
    "occupation_type" TEXT,
    "cnt_fam_members" TEXT,
    "region_rating_client" TEXT,
    "region_rating_client_w_city" TEXT,
    "weekday_appr_process_start" TEXT,
    "hour_appr_process_start" TEXT,
    "reg_region_not_live_region" TEXT,
    "reg_region_not_work_region" TEXT,
    "live_region_not_work_region" TEXT,
    "reg_city_not_live_city" TEXT,
    "reg_city_not_work_city" TEXT,
    "live_city_not_work_city" TEXT,
    "organization_type" TEXT,
    "ext_source_1" TEXT,
    "ext_source_2" TEXT,
    "ext_source_3" TEXT,
    "apartments_avg" TEXT,
    "basementarea_avg" TEXT,
    "years_beginexpluatation_avg" TEXT,
    "years_build_avg" TEXT,
    "commonarea_avg" TEXT,
    "elevators_avg" TEXT,
    "entrances_avg" TEXT,
    "floorsmax_avg" TEXT,
    "floorsmin_avg" TEXT,
    "landarea_avg" TEXT,
    "livingapartments_avg" TEXT,
    "livingarea_avg" TEXT,
    "nonlivingapartments_avg" TEXT,
    "nonlivingarea_avg" TEXT,
    "apartments_mode" TEXT,
    "basementarea_mode" TEXT,
    "years_beginexpluatation_mode" TEXT,
    "years_build_mode" TEXT,
    "commonarea_mode" TEXT,
    "elevators_mode" TEXT,
    "entrances_mode" TEXT,
    "floorsmax_mode" TEXT,
    "floorsmin_mode" TEXT,
    "landarea_mode" TEXT,
    "livingapartments_mode" TEXT,
    "livingarea_mode" TEXT,
    "nonlivingapartments_mode" TEXT,
    "nonlivingarea_mode" TEXT,
    "apartments_medi" TEXT,
    "basementarea_medi" TEXT,
    "years_beginexpluatation_medi" TEXT,
    "years_build_medi" TEXT,
    "commonarea_medi" TEXT,
    "elevators_medi" TEXT,
    "entrances_medi" TEXT,
    "floorsmax_medi" TEXT,
    "floorsmin_medi" TEXT,
    "landarea_medi" TEXT,
    "livingapartments_medi" TEXT,
    "livingarea_medi" TEXT,
    "nonlivingapartments_medi" TEXT,
    "nonlivingarea_medi" TEXT,
    "fondkapremont_mode" TEXT,
    "housetype_mode" TEXT,
    "totalarea_mode" TEXT,
    "wallsmaterial_mode" TEXT,
    "emergencystate_mode" TEXT,
    "obs_30_cnt_social_circle" TEXT,
    "def_30_cnt_social_circle" TEXT,
    "obs_60_cnt_social_circle" TEXT,
    "def_60_cnt_social_circle" TEXT,
    "days_last_phone_change" TEXT,
    "flag_document_2" TEXT,
    "flag_document_3" TEXT,
    "flag_document_4" TEXT,
    "flag_document_5" TEXT,
    "flag_document_6" TEXT,
    "flag_document_7" TEXT,
    "flag_document_8" TEXT,
    "flag_document_9" TEXT,
    "flag_document_10" TEXT,
    "flag_document_11" TEXT,
    "flag_document_12" TEXT,
    "flag_document_13" TEXT,
    "flag_document_14" TEXT,
    "flag_document_15" TEXT,
    "flag_document_16" TEXT,
    "flag_document_17" TEXT,
    "flag_document_18" TEXT,
    "flag_document_19" TEXT,
    "flag_document_20" TEXT,
    "flag_document_21" TEXT,
    "amt_req_credit_bureau_hour" TEXT,
    "amt_req_credit_bureau_day" TEXT,
    "amt_req_credit_bureau_week" TEXT,
    "amt_req_credit_bureau_mon" TEXT,
    "amt_req_credit_bureau_qrt" TEXT,
    "amt_req_credit_bureau_year" TEXT
);

-- Table: raw.application_train
CREATE TABLE IF NOT EXISTS raw.application_train (
    "sk_id_curr" TEXT,
    "target" TEXT,
    "name_contract_type" TEXT,
    "code_gender" TEXT,
    "flag_own_car" TEXT,
    "flag_own_realty" TEXT,
    "cnt_children" TEXT,
    "amt_income_total" TEXT,
    "amt_credit" TEXT,
    "amt_annuity" TEXT,
    "amt_goods_price" TEXT,
    "name_type_suite" TEXT,
    "name_income_type" TEXT,
    "name_education_type" TEXT,
    "name_family_status" TEXT,
    "name_housing_type" TEXT,
    "region_population_relative" TEXT,
    "days_birth" TEXT,
    "days_employed" TEXT,
    "days_registration" TEXT,
    "days_id_publish" TEXT,
    "own_car_age" TEXT,
    "flag_mobil" TEXT,
    "flag_emp_phone" TEXT,
    "flag_work_phone" TEXT,
    "flag_cont_mobile" TEXT,
    "flag_phone" TEXT,
    "flag_email" TEXT,
    "occupation_type" TEXT,
    "cnt_fam_members" TEXT,
    "region_rating_client" TEXT,
    "region_rating_client_w_city" TEXT,
    "weekday_appr_process_start" TEXT,
    "hour_appr_process_start" TEXT,
    "reg_region_not_live_region" TEXT,
    "reg_region_not_work_region" TEXT,
    "live_region_not_work_region" TEXT,
    "reg_city_not_live_city" TEXT,
    "reg_city_not_work_city" TEXT,
    "live_city_not_work_city" TEXT,
    "organization_type" TEXT,
    "ext_source_1" TEXT,
    "ext_source_2" TEXT,
    "ext_source_3" TEXT,
    "apartments_avg" TEXT,
    "basementarea_avg" TEXT,
    "years_beginexpluatation_avg" TEXT,
    "years_build_avg" TEXT,
    "commonarea_avg" TEXT,
    "elevators_avg" TEXT,
    "entrances_avg" TEXT,
    "floorsmax_avg" TEXT,
    "floorsmin_avg" TEXT,
    "landarea_avg" TEXT,
    "livingapartments_avg" TEXT,
    "livingarea_avg" TEXT,
    "nonlivingapartments_avg" TEXT,
    "nonlivingarea_avg" TEXT,
    "apartments_mode" TEXT,
    "basementarea_mode" TEXT,
    "years_beginexpluatation_mode" TEXT,
    "years_build_mode" TEXT,
    "commonarea_mode" TEXT,
    "elevators_mode" TEXT,
    "entrances_mode" TEXT,
    "floorsmax_mode" TEXT,
    "floorsmin_mode" TEXT,
    "landarea_mode" TEXT,
    "livingapartments_mode" TEXT,
    "livingarea_mode" TEXT,
    "nonlivingapartments_mode" TEXT,
    "nonlivingarea_mode" TEXT,
    "apartments_medi" TEXT,
    "basementarea_medi" TEXT,
    "years_beginexpluatation_medi" TEXT,
    "years_build_medi" TEXT,
    "commonarea_medi" TEXT,
    "elevators_medi" TEXT,
    "entrances_medi" TEXT,
    "floorsmax_medi" TEXT,
    "floorsmin_medi" TEXT,
    "landarea_medi" TEXT,
    "livingapartments_medi" TEXT,
    "livingarea_medi" TEXT,
    "nonlivingapartments_medi" TEXT,
    "nonlivingarea_medi" TEXT,
    "fondkapremont_mode" TEXT,
    "housetype_mode" TEXT,
    "totalarea_mode" TEXT,
    "wallsmaterial_mode" TEXT,
    "emergencystate_mode" TEXT,
    "obs_30_cnt_social_circle" TEXT,
    "def_30_cnt_social_circle" TEXT,
    "obs_60_cnt_social_circle" TEXT,
    "def_60_cnt_social_circle" TEXT,
    "days_last_phone_change" TEXT,
    "flag_document_2" TEXT,
    "flag_document_3" TEXT,
    "flag_document_4" TEXT,
    "flag_document_5" TEXT,
    "flag_document_6" TEXT,
    "flag_document_7" TEXT,
    "flag_document_8" TEXT,
    "flag_document_9" TEXT,
    "flag_document_10" TEXT,
    "flag_document_11" TEXT,
    "flag_document_12" TEXT,
    "flag_document_13" TEXT,
    "flag_document_14" TEXT,
    "flag_document_15" TEXT,
    "flag_document_16" TEXT,
    "flag_document_17" TEXT,
    "flag_document_18" TEXT,
    "flag_document_19" TEXT,
    "flag_document_20" TEXT,
    "flag_document_21" TEXT,
    "amt_req_credit_bureau_hour" TEXT,
    "amt_req_credit_bureau_day" TEXT,
    "amt_req_credit_bureau_week" TEXT,
    "amt_req_credit_bureau_mon" TEXT,
    "amt_req_credit_bureau_qrt" TEXT,
    "amt_req_credit_bureau_year" TEXT
);

-- Table: raw.bureau
CREATE TABLE IF NOT EXISTS raw.bureau (
    "sk_id_curr" TEXT,
    "sk_id_bureau" TEXT,
    "credit_active" TEXT,
    "credit_currency" TEXT,
    "days_credit" TEXT,
    "credit_day_overdue" TEXT,
    "days_credit_enddate" TEXT,
    "days_enddate_fact" TEXT,
    "amt_credit_max_overdue" TEXT,
    "cnt_credit_prolong" TEXT,
    "amt_credit_sum" TEXT,
    "amt_credit_sum_debt" TEXT,
    "amt_credit_sum_limit" TEXT,
    "amt_credit_sum_overdue" TEXT,
    "credit_type" TEXT,
    "days_credit_update" TEXT,
    "amt_annuity" TEXT
);

-- Table: raw.bureau_balance
CREATE TABLE IF NOT EXISTS raw.bureau_balance (
    "sk_id_bureau" TEXT,
    "months_balance" TEXT,
    "status" TEXT
);

-- Table: raw.credit_card_balance
CREATE TABLE IF NOT EXISTS raw.credit_card_balance (
    "sk_id_prev" TEXT,
    "sk_id_curr" TEXT,
    "months_balance" TEXT,
    "amt_balance" TEXT,
    "amt_credit_limit_actual" TEXT,
    "amt_drawings_atm_current" TEXT,
    "amt_drawings_current" TEXT,
    "amt_drawings_other_current" TEXT,
    "amt_drawings_pos_current" TEXT,
    "amt_inst_min_regularity" TEXT,
    "amt_payment_current" TEXT,
    "amt_payment_total_current" TEXT,
    "amt_receivable_principal" TEXT,
    "amt_recivable" TEXT,
    "amt_total_receivable" TEXT,
    "cnt_drawings_atm_current" TEXT,
    "cnt_drawings_current" TEXT,
    "cnt_drawings_other_current" TEXT,
    "cnt_drawings_pos_current" TEXT,
    "cnt_instalment_mature_cum" TEXT,
    "name_contract_status" TEXT,
    "sk_dpd" TEXT,
    "sk_dpd_def" TEXT
);

-- Table: raw.homecredit_columns_description
CREATE TABLE IF NOT EXISTS raw.homecredit_columns_description (
    "unnamed: 0" TEXT,
    "table" TEXT,
    "row" TEXT,
    "description" TEXT,
    "special" TEXT
);

-- Table: raw.installments_payments
CREATE TABLE IF NOT EXISTS raw.installments_payments (
    "sk_id_prev" TEXT,
    "sk_id_curr" TEXT,
    "num_instalment_version" TEXT,
    "num_instalment_number" TEXT,
    "days_instalment" TEXT,
    "days_entry_payment" TEXT,
    "amt_instalment" TEXT,
    "amt_payment" TEXT
);

-- Table: raw.pos_cash_balance
CREATE TABLE IF NOT EXISTS raw.pos_cash_balance (
    "sk_id_prev" TEXT,
    "sk_id_curr" TEXT,
    "months_balance" TEXT,
    "cnt_instalment" TEXT,
    "cnt_instalment_future" TEXT,
    "name_contract_status" TEXT,
    "sk_dpd" TEXT,
    "sk_dpd_def" TEXT
);

-- Table: raw.previous_application
CREATE TABLE IF NOT EXISTS raw.previous_application (
    "sk_id_prev" TEXT,
    "sk_id_curr" TEXT,
    "name_contract_type" TEXT,
    "amt_annuity" TEXT,
    "amt_application" TEXT,
    "amt_credit" TEXT,
    "amt_down_payment" TEXT,
    "amt_goods_price" TEXT,
    "weekday_appr_process_start" TEXT,
    "hour_appr_process_start" TEXT,
    "flag_last_appl_per_contract" TEXT,
    "nflag_last_appl_in_day" TEXT,
    "rate_down_payment" TEXT,
    "rate_interest_primary" TEXT,
    "rate_interest_privileged" TEXT,
    "name_cash_loan_purpose" TEXT,
    "name_contract_status" TEXT,
    "days_decision" TEXT,
    "name_payment_type" TEXT,
    "code_reject_reason" TEXT,
    "name_type_suite" TEXT,
    "name_client_type" TEXT,
    "name_goods_category" TEXT,
    "name_portfolio" TEXT,
    "name_product_type" TEXT,
    "channel_type" TEXT,
    "sellerplace_area" TEXT,
    "name_seller_industry" TEXT,
    "cnt_payment" TEXT,
    "name_yield_group" TEXT,
    "product_combination" TEXT,
    "days_first_drawing" TEXT,
    "days_first_due" TEXT,
    "days_last_due_1st_version" TEXT,
    "days_last_due" TEXT,
    "days_termination" TEXT,
    "nflag_insured_on_approval" TEXT
);

-- Table: raw.sample_submission
CREATE TABLE IF NOT EXISTS raw.sample_submission (
    "sk_id_curr" TEXT,
    "target" TEXT
);
